name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@master
    - name: install dependencies
      run: sudo apt install -y libgsl27 libcunit1 libcunit1-doc libcunit1-dev
    - name: make build
      run: make build
  
  run_test:
    runs-on: ubuntu-latest
    steps:
    - name: make test
      run: make test
